<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CETComp>false</CETComp>
    <RootNamespace>KianaBH.GameServer</RootNamespace>
    <StartupObject></StartupObject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>KianaGameServer</AssemblyName>

    <!-- ✅ 关键：支持 Windows / Linux / Android (ARM64) -->
    <RuntimeIdentifiers>win-x64;linux-x64;linux-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\KcpSharp\KcpSharp.csproj" />
    <ProjectReference Include="..\Proto\Proto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" Version="9.0.0" />
  </ItemGroup>
</Project>
